### ISSUE TITLE
positive definiteness of composite kernels

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#10]
Are you sure that a kernel sum of one positive definite and one NOT positive definite kernel is still positive definite ? That's what the code says: `isposdef(ψ::KernelSum) = isposdef(ψ.k1) | isposdef(ψ.k2)`, but I really wouldn't've thought so..

**Comment by trthatcher** [comment]
Hahaha, there was an assumption buried there. I was only going to implement positive (semi) definite kernels. In that case, I believe that one of them being positive definite would be sufficient for the composite to be positive definite (correct me if I'm wrong - I could very well be... I didn't study much in the way of analysis).

Many of the kernels I have right now were just an initial set and I hadn't read up on them as of yet. I feel like at least one of them is not not necessarily PSD. Did you want non PSD kernels supported? Are they used anywhere?

**Comment by st--** [comment]
No, any kernel I want should at least be semi-posdef. I'm not particularly deep into properties of kernels, but based on what I just read up on positive definiteness of matrices I think isposdef(KernelSum) should use `&` instead of `|`. Will add that to the next pull request.

(On a side note, for what do you use your Kernel package?)

**Comment by trthatcher** [comment]
So I was reading a bit more into the definitions. What I've referred to as "positive definiteness" is "strict positive definiteness" for kernels (the analogue for matrices is "positive semidefinite" and "positive definite" respectively"). 

A strict positive definite kernel will return a positive definite gramian matrix.
A positive definite kernel will return a positive semidefinite gramian matrix.

A matrix S is positive definite if x'Sx > 0 for all x != 0 and semidefinite if it is a '>=' inequality.

The kernel sum corresponds to a sum of two gramians and the kernel product corresponds to the hadamard product of two gramians. 

[Shur product theorem](http://en.wikipedia.org/wiki/Schur_product_theorem) shows us that we are correct for the kernel product (using '&').

However, if A is positive semidefinite and B is positive definite, then:

x'Ax >= 0
x'Bx > 0
==>
0 < x'Ax + x'Bx = x'(A + B)x

So I think it should be '|' if we're restricting our set of kernels to positive definite ones. Do you concur? 

I was going to go through and learn all the major ML and statistical techniques. I started with data preprocessing algorithms. I was working on kernel fisher discriminant analysis and KPCA... but shifted focus to making a kernel matrix package because I felt there was a need for it. This is all just educational for me..

**Comment by trthatcher** [comment]
Conditionally positive definite kernels are included in the package, so I agree with your change.
