### ISSUE TITLE
sqdist_d*() and scprod_d*()

### ISSUE THREAD

**Issue by trthatcher** [trthatcher/MLKernels.jl#18]
It seems like each version is used in only one place (the derivative for the corresponding class of kernel including ARD). Making use of these functions uses at least two - currently three - scans of the array that the kernel function returns.

Are these functions providing any real value? It seems like there's two definitions with multiple array scans when only a single definition and one scan is required.

**Comment by st--** [comment]
Do you mean 'multiple array scans' because we need both scprod() and scprod_d*(), and each goes through the array once? Where's the third scan?

And of course we can rewrite the code such that it calculates scprod and derivatives in a single pass. However, I think it'd be worthwhile to have a simple reference implementation which is easy to understand and easy to check for correctness, even if slow, to compare with the fast, specialised routines - to make sure those work correctly, and if not, to make it easier to debug...

**Comment by trthatcher** [comment]
Yes, a simple function for reference would be perfect.

Sorry, I'll clarify. If we were looking at getting the derivative with respect to x and y for kernel(x,y) = kappa(z(x,y), it was something like: 

kappa_dz2(z(x,y))*(dz/dx)*(dz/dy)' + kappa_dz(z(x,y))*(dz2/dxdy) 

which could be implemented (WLOG): 

kappa_dz2(sqdist(x,y)) * sqdist_dx  sqdist_dy' + kappa_dz(sqdist(x,y)) * (sqdist_dxdy)

The way it was being calculated for kernel_dxdy for both scprod and sqdist was:
1. Compute sqdist(x,y), kappa_dz(sqdist(x,y)), kappa_dz2(sqdist(x,y)) which takes one full scan
2. Compute K = sqdist_dx * sqdist_dy' which took one full scan
3. Scale K by kappa_dz2(sqdist(x,y)) which took one full array scan
4. Add kappa_dz(sqdist(x,y)) * (sqdist_dxdy) to K which takes diagonal array scan

I was just saying that if we don't use sqdist_dx, sqdist_dy and sqdist_dxdy... we can collapse steps 2-4 into a single function (kernel_dxdy) with one array scan. I don't _think_ it would be a big deal because it seems like we only use sqdist_d\* in one place - the corresponding kernel_d*.

I've changed things for the sqdist and scprod functions to use only one scan. We would just need similar definitions for ARD kernels.
