### ISSUE TITLE
GammaRationalQuadraticKernel parameters

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#22]
So GammaRationalQuadraticKernel(alpha,beta,gamma) is a generalised form of the RationalQuadraticKernel(alpha,beta) is a generalised form of the InverseQuadraticKernel(alpha).
InverseQuadraticKernel(alpha) = RationalQuadraticKernel(alpha,beta=1), and
RationalQuadraticKernel(alpha,beta) = GammaRationalQuadraticKernel(alpha,beta,gamma=1).
But the default value of GammaRationalQuadraticKernel is gamma=0.5. Just checking if that is intentional?

**Comment by st--** [comment]
Also, is the reason for 0 < gamma <= 1 that otherwise it's not a pos.def. kernel, or what ?

**Comment by st--** [comment]
Also also: for these 'series' of kernels, should we have tests to assure that e.g. InverseQuadraticKernel(alpha) == RationalQuadraticKernel(alpha,beta=1)?

On that note... what's the point of all the convert() definitions from e.g. InverseQuadraticKernel to QuadraticKernel{T} ? I don't feel like I really grasp yet the point of that..

**Comment by trthatcher** [comment]
I would look at the from the other direction... IE RationalQuadraticKernel is a special case of GammaRationalQuadraticKernel. It seemed kind of odd to me to default a general form to a special case, so it was intentional. But if you disagree, that's no problem.

Regarding the gamma restriction, you are correct. There's some very explicit forms that positive and negative definite kernels can take when the kernel isn't a separable function. You can check out chapter 3 in "Harmonic Analysis on Semigroups - Theory of Positive Definite and Related Functions" by Berg.

QuadraticKernel is the parent abstract type - it's the same idea as converting a SquaredExponential{Float64} to SquaredDistance{Float32}. You're just changing the data type of the parameters using the parent type.

**Comment by st--** [comment]
I don't know; I mean, if you supply a default value, there must be some thought in there - if there's no reason to pick any default value, it'd be better to leave it out - I think it's fine to leave it as is e.g. if both gamma=0.5 and gamma=1.0 are the two most-often used cases, then people can simply use GammaRationalQuadratic() and RationalQuadratic(), respectively... Depends a bit on whether you think of it as just providing optimised (hard-coded) versions for special cases of the parameters, or whether it's providing different often-used variants?

**Comment by st--** [comment]
Oh, and so the point of all the convert declarations is so that if I need to go from Float64 to Float32 or vice versa but don't want to specify an 'end type' in my code? Cool. If you don't have objections I was just thinking of code-generating all those - i.e. traversing the `subtypes(StandardKernel)` tree, then using `names(kerneltype)` to figure out the fields that need to be converted, and doing all of them in one go rather than having `convert`s dotted around everywhere (and the chance of missing one out)...

**Comment by trthatcher** [comment]
Please do scan the type tree and define the conversions, that would be so much easier!

**Comment by st--** [comment]
Already done: 2bc4c27f27c0c896f9757ed7f8c6ba6aac1ac696 :-)

**Comment by trthatcher** [comment]
Recent changes should have addressed any concerns here. There's now a "value dispatch" that will use more efficient versions of `kappa` depending on the parameter values for the kernel. This renders the special case types redundant, so I removed them.
