### ISSUE TITLE
Remove Separable Kernel (Mercer Sigmoid Kernel)

### ISSUE THREAD

**Issue by trthatcher** [trthatcher/MLKernels.jl#25]
The separable kernel is the dot product kernel applied to an element-wise transformation of the original data vectors. The element-wise transformation is 100% equivalent to pre-processing one's data.

I don't think it's adding any value - any opposition to removal of this type/kernel?

**Comment by st--** [comment]
I don't know; the Periodic kernel is also equivalent to a pre-processing transform of the Squared-Exponential kernel - but in that case I think it'd still be useful to have it directly available rather than having to figure out transforms yourself. So, yes, in some sense it's not "needed" - but I'd base it on how useful it is. I'd never heard of the Mercer Sigmoid Kernel, but then I'm not that closely involved with kernel methods after all: If it's something which would routinely get used, I'd suggest to keep it in. If there'd be no-one using it, we might as well kick it out and reduce the amount of code to be maintained.
