### ISSUE TITLE
Limits on parameter ranges: PolynomialKernel,

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#28]
PolynomialKernel required d to be integer. ExponentialKernel, RationalQuadraticKernel, PowerKernel, LogKernel all require gamma to be <= 1. What's the reason for that ? (Maybe a kernel would not be Mercer if gamma > 1 (or d real, for PolynomialKernel), but it might still be useful. We could just amend ismercer() so that it actually checks the parameter value?)

**Comment by trthatcher** [comment]
All these kernels and their restrictions actually arise from a couple theorems that will let you construct kernels:
- k(x,y) = ||x-y||^2 is negative definite
- If negative definite k >= 0 always, then k(x,y)^t where t in (0,1] is negative definite
- If negative definite k >= 0 always, then log(1 + k(x,y)) is negative definite

So above is all your negative definite kernels - you can construct the power kernel and log kernel using the above and by noting that if k is negative definite, then -k is conditionally positive definite. Then you can use the following:
- x'y is positive definite
- k is negative definite iff exp(-t*k(x,y)) is positive definite for all t > 0
- a*k1(x,y)*k2(x,y) is positive definite if k1 and k2 are positive definite and a > 0
- k1(x,y) + k2(x,y) is positive definite if k1 and k2 are positive definite

From that you can construct the rational quadratic, exponential and polynomial kernels.

As for the relaxation of restrictions - I'm inclined not to. If we did that, it would restrict the polynomial kernel to the upper right quadrant since we would impose the restriction x'y >= 0 for certain d. I think that would definitely cause some confusion. When I clean up the documentation, I will give a small description of each of the kernels and cover any constraints. I think if someone truly needed a different parameter value, they would tweak the code themselves or define a new kernel.

**Comment by st--** [comment]
Humm, ok... And I hadn't thought of x^d for negative x and fractional d being undefined! >_< So I'll roll that back. Can't have a derivative for a discrete quantity, so I'll just kick out kappa_dd(::PolynomialKernel,...). Should probably throw an exception - which one would you suggest ? It's not exactly an ArgumentError, is it...

**Comment by trthatcher** [comment]
I would just use the generic `error` function and specify the problem. You could always compute a finite difference... d:

I'd definitely like to keep the restrictions on by default - I want to ensure the integrity of the Mercer kernel type for non advanced users. However, I don't have anything against adding a boolean flag (or something of the like) to allow users to input which ever values they like.

**Comment by st--** [comment]
The finite difference between integer values? e.g. for f'(d=2), (f(d=3)-f(d=1))/2? I don't know how much sense that makes...

We can ensure the integrity of _Mercer_ kernel types by having ismercer inspect the actual values of the kernel parameters, and e.g. only return true if gamma<=1? But I'm not too fussed about it, we can also just leave it as a hard constraint on the type.

**Comment by trthatcher** [comment]
Don't worry - I'm joking. Finite difference is sometimes referred to as discrete calculus.

I think for now I would prefer to keep the constraints.
