### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#29]
I was going to add `@test_throw` tests for the various ArgumentErrors e.g. in kernelmatrix, and to figure out which way around things should go I played around in the REPL with things like `MLKernels.kernelmatrix!(zeros(4,4), ExponentialKernel(), ones(4,6), true)`, transposed dimensions for X, different values for is_trans, leaving out is_trans entirely - which sometimes led to instant segfaults, sometimes with a bit of delay. Don't have the time anymore to investigate, but I suspect it's something where we used `@inbounds` but didn't have enough checks to make sure we weren't going to exceed the array bounds!

**Comment by trthatcher** [comment]
Odd, I'll look into this. ExponentialKernel should call scprodmatrix! when it actually comes to the actual matrix multiplication. This will call either BLAS.syrk! or BLAS.gemm! which does a dimension check before calling the external BLAS library. I would have expected a dimension mismatch error... I might have made an error when I updated it yesterday, but I'll have to check.

Other than that, it would have to be in kappa_array!

**Comment by trthatcher** [comment]
-________________________-

When I adjusted sqdistmatrix! to allow for overwriting of a matrix, I wrote `n = is_trans ? 1 : 2` rather than `n = is_trans ? 2 : 1` in one place. So it failed when calculating `K = kernelmatrix(k,X)` when `k` was a squared distance kernel and `X` rectangular.

Also, I found out BLAS.gemm! only does a partial dimension check... so I added in a set of checks.
