### ISSUE TITLE
MultiQuadraticKernel missing

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#32]
Maybe that's intentional, but I just noticed that the MultiQuadraticKernel in master doesn't have any equivalent in developments. The InverseMultiQuadraticKernel maps to RationalQuadraticKernel with beta=0.5, but the MultiQuadraticKernel would be beta=-0.5 and you only allow positive values for beta...

**Comment by trthatcher** [comment]
Hmmm, just thinking. I removed it originally because I didn't find anything written on it. I actually did the kernel readings so now I'm more familiar with the math of it anyway.

It's a conditionally positive definite kernel - it can be derived by translating the squared distance (negative definite) and then using that theorem with phi^t with 0 < t <= 1. Then we would negative it to make it conditionally positive definite, otherwise it's negative definite.

I kind of see it as an extension of the power kernel... just that the translation is within the square root. 

Do you want to see it included?

**Comment by trthatcher** [comment]
Does not add value.
