### ISSUE TITLE
Kernel derivatives need to be a separate package

### ISSUE THREAD

**Issue by trthatcher** [trthatcher/MLKernels.jl#33]
@st-- 

I'm trying to be pragmatic when it comes to this package. I originally envisioned that this package would provide the following:
- A vetted set of mainstream machine learning kernels (with some simple combination rules)
- The ability to compute a kernel matrix quickly
- The ability to compute a kernel matrix approximation

Unfortunately with the kernel derivatives, I feel the package moves too far away from that. My concerns are that: 
- Derivatives may not be defined and vector parameters add a layer of complexity
- Many derivatives that do exist are intractable - reliance on analytic derivatives is complex/unfeasible in many cases and raises floating point accuracy in others
- Derivatives appear to be catering to a very specific need - it's a specialized component being added to a generic package. 

As such, it's bespoke code and necessitates its own package. 

That being said, I appreciate all the help and I'm more than willing to help you out where ever I can.

**Comment by st--** [comment]
Well, I still wouldn't say derivatives are a "very specific need" - whenever you want to automatically optimise parameters, you need derivatives w.r.t. the parameters, and whenever you want to deal with functions and their derivatives (e.g. in GP regression) you need derivatives w.r.t. x and y, so I disagree that it _necessitates_ its own package.

Fortunately the way Julia works you can simply extend types from other packages, so that way it ought to be possible to just move them into a new MLKernelDerivatives.jl or something like that. My only concern is that derivatives ARE very intimately linked to the original functions, and it'd be a very dependent package (if you changed a parameter name in a kernel type, that would then have to be reflected in the derivatives - which would be easier to keep track of if they're defined right next to each other)... but I guess we can try how it works out?

You changed so much recently that I've lost track. I saw you adding KernelPath somethings, and I think I get what you were trying, but could you briefly explain that in your own words anyway ?

Also, if you could just write down in a bit more detail than the commit messages all that you changed since my last commit, that'd be appreciated! If I understand it right, the new 'derivatives' branch is what used to be developments, and developments is as it was before but with all the derivative code removed ?

**Comment by trthatcher** [comment]
I completely understand where you're coming from, but I think there needs to be a lot of care taken with the parameter derivatives and how they're defined from a user perspective. I'll add a little commentary later... perhaps a separate package isn't necessary... but I'll want to talk scope/timeline/approach.

Unfortunately I don't have much time, so here's a quick brain dump that will hopefully help with your other questions:

Derivatives is a branch with all the function derivatives intact. I just added a KernelVariable type that will generate a list of expressions corresponding to the path through the kernel operations and encodes the parameter name in the type parameter.

ex SubVariable{:alpha}{ [k[5], k[2], k[3]] } . the `generatepath()` function would return k[5].k[2].k[3].alpha

This should make computing derivatives of composite kernel parameters more straight forward in terms of indexing...

Development is a stripped down version of the package with only the `kernel` and `kernelmatrix`. I pulled the periodic kernel out for now in the interest of getting something out. I added the Matern kernel. The kernel sum can now accept a positive real number (translate a kernel) - this is a valid operation. I collapsed the vector and matrix functions into one file - there was overlap starting to happen.
