### ISSUE TITLE
julia 0.6 compatibility

### ISSUE THREAD

**Issue by gdkrmr** [trthatcher/MLKernels.jl#51]
What are your plans on supporting Julia 0.6?

**Comment by gdkrmr** [comment]
great! Thanks!

**Comment by trthatcher** [comment]
I'm going to make this the next task - so should be in the next week or so. I've not tested Julia `0.6`, so I'm not sure how much needs to change yet. I'll be eliminating any deprecation warnings.

**Comment by juliohm** [comment]
Can you please confirm that there is no support for Julia v0.6 yet?

**Comment by trthatcher** [comment]
Julia 0.6 is fully supported in the `dev` branch.

**Comment by juliohm** [comment]
:disappointed: could you please explain why dev instead of master? I wasted time yesterday preparing a PR because there is no documentation about dev anywhere. I will close the PR.

Could you please merge the branch and tag a new release?

**Comment by trthatcher** [comment]
@juliohm I really appreciate you taking an interest in the project and helping out. I'm sorry for the lack of clarity around the branches - I didn't mean to waste your time. I'll stick to master to ensure this doesn't happen a second time. Again, sorry for the confusion.

There's an outstanding issue that I hadn't found the root of and it was causing the occasional Travis build to fail, which is why I hadn't merged yet with master. The cause has been identified so the solution is clear - see issue #53. I'll tag a new version once that is resolved.

**Comment by juliohm** [comment]
Thank you @trthatcher, that is really helpful already. I am planning to release a new GeoStats.jl solver soon that depends on MLKernels.jl, since the cause of #53 is now identified, I think it makes things easier.

I will wait for the new tag and then submit the registration request.
