### ISSUE TITLE
Composited composite kernels

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#7]
Currently, a CompositeKernel can only be made out of StandardKernels, which means something like GaussianKernel()+GaussianKernel()*GaussianKernel() doesn't work. Is there a good reason for that?

**Comment by trthatcher** [comment]
I read that Julia isn't exactly speedy when it comes to recursion, which is the direction this is heading in. Originally, I just thought I'd keep it simple. 

I don't mind adding that, but it complicates efficient calculation of the kernel matrix and any kind of derivatives. No idea what performance could even look like... but maybe I'm worrying prematurely.

If it were to be added in, I would just change the composite kernels into two types. Keep the scaled kernel thing as a leaf, but then make a branch type with an operation field specifying whether to add or multiply. 

What were you thinking?

**Comment by st--** [comment]
Maybe I don't exactly understand what you mean, but why would you want to conflate KernelSum and KernelProduct into a single type with an operation field ?

Speed-wise, I think it shouldn't be too much of an issue as long as there are separate kernelmatrix() functions which do the recursion _outside_ of having constructed large matrices, rather than recursing for every single element (inside the matrix construction).

**Comment by trthatcher** [comment]
No, you're right. It would be best to keep them as separate types because they have very different properties. If the operations had similar properties, I would just halve the code by making a generic kernel operation type that would call one operation or another when it came time to evaluate.

If we were to model the operations as a binary tree, I'm seeing one difficulty. Consider this tree:
+(*(k1,+(k2,k3)), ...)

One approach (the one I currently take): calculate the entire kernel matrix at once (or calculate gramian and then 'kernelize'). If we strictly had Kernel Sums, you could just keep adding the kernel matrices up and compute at most two gramians at a time (memory stays under control). However, the multiplication adds a wrinkle because you need have both branches fully calculated to evaluate the product.

Alternatively, you could calculate each entry in the kernel matrix and traverse the tree of kernel operations. I've tried composing functions recursively in Julia. I couldn't get them to perform well at all, but that didn't surprise me.

But maybe I'm over complicating things. Instead of (A+B)*(C+D), you could expand things into AC + AD + BC + BD, which is straight forward to compute but could be wasteful with calculating each matrix twice.

What was your approach going to be?

**Comment by trthatcher** [comment]
@st-- Could you please make a separate branch when you start experimenting with a recursive implementation of the kernel operations? Thanks!

Also, how are you planning on managing the memory usage?
