### ISSUE TITLE
Kernel function discussion/kernels with variable-dimensional parameters (ARD)

### ISSUE THREAD

**Issue by st--** [trthatcher/MLKernels.jl#9]
I just pushed an implementation of integer-based parameter derivatives based on calling names() on the kernel object to get its field. After all that I remembered an important use case in Gaussian Processes: the "Automatic Relevance Determination" (ARD) kernel. This is basically a Gaussian kernel, but with a sigma _vector_ (same length as data dimension):

Instead of the 1D Gaussian, `exp(- vecnorm(x - y)^2 / 2k.sigma^2)`, you would use `exp(- vecnorm((x - y) ./ k.sigmas)^2 / 2)`, where k.sigmas is a vector of the same dimensions as x and y.

This crops up not just for euclidean distance kernels, but also scalar product kernels - e.g. a LinearKernel with different scaling for each dimension...

Any idea on how to best implement that ?

**Comment by trthatcher** [comment]
I created a [gist](https://gist.github.com/trthatcher/9919efeb6e97e7010374).

The non-weighted version can just point directly to Base.dot.

I don't foresee any difficulties in adding this. I'll just have to make the equivalent weighted gramian matrix functions.

**Comment by trthatcher** [comment]
I closed the other issue as I think we can have all discussion regarding the vector kernel calculation here.

Here's my recommendations for implementation of the vector calculations for kernel functions:

[gist](https://gist.github.com/trthatcher/b8999881a97a6e5d942f)

**Comment by trthatcher** [comment]
PS

You're contributing a lot. I think you're easy to work with and very reasonable. Would you like me to add you as a contributor? This effectively means you're a co-owner. I'm cool with that!

**Comment by st--** [comment]
Looks good. For very large vectors, BLAS.dot is indeed faster than your scprod(), but if you swap around the values of n and k (i.e., lots of dot products of small vectors), then the inline version is faster by a factor of 3.5. (Less function-calling overhead?) At least for GPs the dimensions tend to be in the order of 10s, not 1000s, I think, so I'd go for using scprod() instead of BLAS.dot. (Well, and you could always do `MLKernels.scprod(x,y) = BLAS.dot(x,y)` in your code if you want to do that...)

Would be happy with being added as contributor. Don't know what that means on github/how it works, but I'm sure I'll find out!

**Comment by st--** [comment]
I think scprod(x,y,w) and sqdist(x,y,w) should use w as a multiplicative weight; it's faster to deal with inverse w = 1./sigmas rather than division everywhere... also makes the derivatives simpler!

**Comment by trthatcher** [comment]
Quick question about ARD when it is applicable to scalar product form kernels

Right now the weights are squared for euclidean distances: 
- (diagm(w)(x-y))'(diagm(w)(x-y)) = (x-y)' * diagm(w .^2) * (x-y)

For scalar products, they are not:
- (diagm(sqrt(w))(x))'(diagm(sqrt(w))(y)) = x' * diagm(w) * y

Is this how they are defined in the literature? I've only found ARD discussions on euclidean distance type kernels. It seems like a little bit of an incongruity from a definition point of view. I would think the weights should be squared for scalar products. IE w_i is your scaling factor rather than sqrt(w_i)... that or both euclidean distance and scalar prod should use sqrt.

**Comment by st--** [comment]
Um, I don't know if there's a consensus on definition. In the end it doesn't matter; it's just parameters, whether it's squared or not. If you prefer w.^2 for ScalarProductKernels, go for it, I don't mind either way.

On another note: I think the weights should belong to the kernel object; in the end they're just a (perhaps slightly more complicated) kind of parameter. Hence they shouldn't be parameters to the kernel_* functions...

**Comment by st--** [comment]
(Also, I think it'd be better to think of ARD as a kind of Composite kernel, and have kernel_dp(k, :weights) and then e.g. kernel_dp(k, symbol("k.sigma")) for an ARD{GaussianKernel} object; otherwise a new SquaredDistanceKernel with a parameter w would be silently shadowed by w->weights.)

**Comment by trthatcher** [comment]
Sure. The main reason I defined `kernel_dw(k, x, y, w)`  and `kernel(k, x, y, w)` is because the `w` can actually be applied to any kernel that exists. That being said, I'm not opposed in any way to changing it back.

I have a proposal, however. There's a theorem:

If h: Rⁿ -> Rᵈ and k is a kernel in Rᵈ, then if x and y ∈ Rⁿ we have that k(h(x),h(y)) is a kernel in Rⁿ.

ARD is the case where k(x,y) = k(diagm(w)*x, daigm(w)*y). 

I'd like to extend ARD so that the 'weights' can be an arbitrary matrix. IE support the case where h() is a centered linear function of x and y. We can still have a vector case for ARD that would correspond to what you use it for.

**Comment by st--** [comment]
Aren't there kernels which are neither scalar product nor squared distance nor separable? How to apply weights very much depends on the structure of the kernel. Each new type would need a new implementation of kernel(k, x, y, w) anyway - I think it's neater to keep that together in kernel(::ARD) rather than extending the signature. Gonna change it back :)

I'm actually currently investigating a k(h(x),h(y)) in my research ... though with a much more general h(x), and there it's easier to preprocess the data than try to shoehorn it into our code...

Do you think it'd be sensible to have a single type deal simultaneously with weights::Vector and some kind of arbitrary matrix ? Might be simpler to have a separate type for those (and then we wouldn't need to provide derivatives w.r.t. all the matrix elements for the latter; I think that'd be too much hassle, and with so many parameters I don't know if optimization on parameters would work anyway...)?

**Comment by trthatcher** [comment]
Yup, please do change the kernel(...,w)... I hadn't had a chance to change it.

Actually, having played around with the idea of an arbitrary matrix... I came to the same conclusion as your second point. h() can be done on the pre-processing side of things. There's a bunch of extra code just to do a simple linear function. It's probably better to leave that to the user.

**Comment by trthatcher** [comment]
ARD kernel now supported.
